// AUTO-GENERATED by fetch_data.py  –  25.06.2026 10:56
// Do not edit manually. Re-fetch: python3 fetch_data.py

const LIVE_DATA = {
  "fetchedAt": "25.06.2026 10:56",
  "ytdYear": 2026,
  "mainMarkets": {
    "Emerging Market Equities": {
      "ytd": 23.11,
      "w52Low": -14.94,
      "w52High": 27.88,
      "l30d": 6.07,
      "etfProxy": true,
      "ticker": "EEM"
    },
    "Japanese Equities": {
      "ytd": 17.26,
      "w52Low": -13.77,
      "w52High": 20.25,
      "l30d": 5.07,
      "etfProxy": true,
      "ticker": "EWJ"
    },
    "Global Equities – Small Caps": {
      "ytd": 17.03,
      "w52Low": -9.94,
      "w52High": 17.03,
      "l30d": 5.65,
      "etfProxy": true,
      "ticker": "IUSN.DE"
    },
    "US Equities (S&P 500)": {
      "ytd": 10.51,
      "w52Low": -8.74,
      "w52High": 11.35,
      "l30d": 1.92,
      "etfProxy": true,
      "ticker": "SPY"
    },
    "Global Equities": {
      "ytd": 11.58,
      "w52Low": -9.62,
      "w52High": 12.47,
      "l30d": 2.87,
      "etfProxy": true,
      "ticker": "ACWI"
    },
    "Global Equities Ex-US (MSCI W ex USA)": {
      "ytd": 8.32,
      "w52Low": -9.62,
      "w52High": 9.23,
      "l30d": 1.37,
      "etfProxy": true,
      "ticker": "IWQU.L"
    },
    "Pacific ex Japan Equities": {
      "ytd": 7.74,
      "w52Low": -4.64,
      "w52High": 9.54,
      "l30d": 1.17,
      "etfProxy": true,
      "ticker": "EPP"
    },
    "Swiss Equities – Small Caps": {
      "ytd": 8.57,
      "w52Low": -7.26,
      "w52High": 8.57,
      "l30d": 6.84,
      "etfProxy": true,
      "ticker": "CSSMIM.SW"
    },
    "UK Equities": {
      "ytd": 6.2,
      "w52Low": -11.89,
      "w52High": 7.11,
      "l30d": 1.21,
      "etfProxy": true,
      "ticker": "EWU"
    },
    "Swiss Equities (SPI)": {
      "ytd": 9.47,
      "w52Low": -9.31,
      "w52High": 9.47,
      "l30d": 4.77,
      "etfProxy": true,
      "ticker": "CHSPI.SW"
    },
    "Eurozone Equities (EURO STOXX 50)": {
      "ytd": 6.73,
      "w52Low": -12.06,
      "w52High": 9.05,
      "l30d": 4.65,
      "etfProxy": true,
      "ticker": "FEZ"
    },
    "US Real Estate (Equities)": {
      "ytd": 14.44,
      "w52Low": -1.33,
      "w52High": 14.44,
      "l30d": 4.55,
      "etfProxy": true,
      "ticker": "VNQ"
    },
    "Swiss Real Estate (SXI Broad)": {
      "ytd": 0.72,
      "w52Low": -6.85,
      "w52High": 3.83,
      "l30d": 1.11,
      "etfProxy": true,
      "ticker": "SRFCHA.SW"
    },
    "European Real Estate (Equities)": {
      "ytd": 2.31,
      "w52Low": -3.71,
      "w52High": 11.62,
      "l30d": 1.4,
      "etfProxy": true,
      "ticker": "IPRP.AS"
    },
    "Asian Real Estate (Equities)": {
      "ytd": -1.18,
      "w52Low": -6.8,
      "w52High": 5.11,
      "l30d": 1.94,
      "etfProxy": true,
      "ticker": "RWX"
    },
    "Commodities (Diversified, unhedged)": {
      "ytd": 16.19,
      "w52Low": -8.23,
      "w52High": 29.16,
      "l30d": -8.84,
      "etfProxy": true,
      "ticker": "ICOM.L"
    },
    "Gold Bullion (unhedged)": {
      "ytd": -6.28,
      "w52Low": -23.89,
      "w52High": 16.73,
      "l30d": -8.73,
      "etfProxy": true,
      "ticker": "ZGLD.SW"
    },
    "CHF Bonds": {
      "ytd": 0.58,
      "w52Low": -1.69,
      "w52High": 0.89,
      "l30d": 0.73,
      "etfProxy": true,
      "ticker": "CHCORP.SW"
    },
    "EM Bonds Local Currency": {
      "ytd": 3.56,
      "w52Low": -5.29,
      "w52High": 3.57,
      "l30d": 4.06,
      "etfProxy": true,
      "ticker": "EMLC"
    },
    "Global Bonds (CHF hedged)": {
      "ytd": -0.23,
      "w52Low": -1.78,
      "w52High": 1.05,
      "l30d": 0.9,
      "etfProxy": true,
      "ticker": "AGGH.SW"
    },
    "EUR Bonds": {
      "ytd": 0.14,
      "w52Low": -2.73,
      "w52High": 13.72,
      "l30d": 1.82,
      "etfProxy": true,
      "ticker": "IBGE.L"
    },
    "USD Bonds": {
      "ytd": 3.43,
      "w52Low": -3.68,
      "w52High": 3.43,
      "l30d": 4.51,
      "etfProxy": true,
      "ticker": "AGG"
    },
    "CHF Corporate Bonds": {
      "ytd": 0.58,
      "w52Low": -1.69,
      "w52High": 0.89,
      "l30d": 0.73,
      "etfProxy": true,
      "ticker": "CHCORP.SW"
    },
    "USD Corporate Bonds": {
      "ytd": 3.66,
      "w52Low": -3.61,
      "w52High": 3.66,
      "l30d": 4.76,
      "etfProxy": true,
      "ticker": "LQD"
    },
    "EUR Corporate Bonds": {
      "ytd": 0.58,
      "w52Low": -2.47,
      "w52High": 1.17,
      "l30d": 2.13,
      "etfProxy": true,
      "ticker": "IEAC.AS"
    },
    "Inflation Linked": {
      "ytd": 3.62,
      "w52Low": -2.22,
      "w52High": 3.62,
      "l30d": 3.57,
      "etfProxy": true,
      "ticker": "TIP"
    },
    "Money Market CHF": {
      "ytd": 0.27,
      "w52Low": -3.13,
      "w52High": 1.68,
      "l30d": 2.73,
      "etfProxy": true,
      "ticker": "CSBGC0.SW"
    },
    "Money Market GBP": {
      "ytd": 2.25,
      "w52Low": -2.49,
      "w52High": 2.25,
      "l30d": 1.81,
      "etfProxy": true,
      "ticker": "CSH2.L"
    },
    "Money Market USD": {
      "ytd": 4.1,
      "w52Low": -2.45,
      "w52High": 4.1,
      "l30d": 3.68,
      "etfProxy": true,
      "ticker": "BIL"
    },
    "Money Market EUR": {
      "ytd": -0.22,
      "w52Low": -2.79,
      "w52High": 0.88,
      "l30d": 1.43,
      "etfProxy": true,
      "ticker": "EXVM.DE"
    },
    "USD / CHF": {
      "ytd": 2.42,
      "w52Low": -2.83,
      "w52High": 2.77,
      "l30d": 3.38,
      "etfProxy": true,
      "ticker": "USDCHF=X"
    },
    "EUR / CHF": {
      "ytd": -0.84,
      "w52Low": -3.02,
      "w52High": 1.49,
      "l30d": 1.19,
      "etfProxy": true,
      "ticker": "EURCHF=X"
    },
    "JPY / CHF": {
      "ytd": -0.71,
      "w52Low": -2.81,
      "w52High": 9.27,
      "l30d": 1.6,
      "etfProxy": true,
      "ticker": "JPYCHF=X"
    }
  },
  "subMarkets": {
    "Emerging Market Equities": {
      "Taiwan": {
        "ytd": 65.59,
        "w52Low": -13.47,
        "w52High": 72.53,
        "l30d": 11.79,
        "etfProxy": true,
        "ticker": "EWT"
      },
      "China": {
        "ytd": -14.81,
        "w52Low": -14.81,
        "w52High": 5.4,
        "l30d": -3.64,
        "etfProxy": true,
        "ticker": "MCHI"
      },
      "South Korea": {
        "ytd": 97.64,
        "w52Low": -31.39,
        "w52High": 117.86,
        "l30d": 12.03,
        "etfProxy": true,
        "ticker": "EWY"
      },
      "India": {
        "ytd": -6.84,
        "w52Low": -15.69,
        "w52High": 4.56,
        "l30d": 6.03,
        "etfProxy": true,
        "ticker": "INDA"
      },
      "South Africa": {
        "ytd": -6.23,
        "w52Low": -27.22,
        "w52High": 14.49,
        "l30d": -2.41,
        "etfProxy": true,
        "ticker": "EZA"
      },
      "Brazil": {
        "ytd": 9.06,
        "w52Low": -19.19,
        "w52High": 28.35,
        "l30d": -2.87,
        "etfProxy": true,
        "ticker": "EWZ"
      },
      "Saudi Arabia": {
        "ytd": 7.69,
        "w52Low": -1.57,
        "w52High": 10.21,
        "l30d": 3.44,
        "etfProxy": true,
        "ticker": "KSA"
      },
      "Mexico": {
        "ytd": 10.09,
        "w52Low": -15.12,
        "w52High": 14.21,
        "l30d": -0.46,
        "etfProxy": true,
        "ticker": "EWW"
      },
      "UAE": {
        "ytd": 9.34,
        "w52Low": -9.59,
        "w52High": 10.95,
        "l30d": 12.11,
        "etfProxy": true,
        "ticker": "UAE"
      },
      "Indonesia": {
        "ytd": -34.81,
        "w52Low": -39.91,
        "w52High": 3.24,
        "l30d": -5.54,
        "etfProxy": true,
        "ticker": "EIDO"
      },
      "Thailand": {
        "ytd": 21.1,
        "w52Low": -16.33,
        "w52High": 25.19,
        "l30d": 0.88,
        "etfProxy": true,
        "ticker": "THD"
      }
    },
    "US Equities (S&P 500)": {
      "Nasdaq 100": {
        "ytd": 18.99,
        "w52Low": -9.34,
        "w52High": 22.88,
        "l30d": 2.49,
        "etfProxy": true,
        "ticker": "QQQ"
      },
      "Russell 2000": {
        "ytd": 22.65,
        "w52Low": -12.86,
        "w52High": 22.65,
        "l30d": 7.83,
        "etfProxy": true,
        "ticker": "IWM"
      }
    },
    "Swiss Equities (SPI)": {
      "SMI": {
        "ytd": 9.22,
        "w52Low": -10.86,
        "w52High": 9.22,
        "l30d": 4.48,
        "etfProxy": true,
        "ticker": "CSSMI.SW"
      },
      "SPI Extra": {
        "ytd": 8.57,
        "w52Low": -7.26,
        "w52High": 8.57,
        "l30d": 6.84,
        "etfProxy": true,
        "ticker": "CSSMIM.SW"
      }
    },
    "Eurozone Equities (EURO STOXX 50)": {
      "France": {
        "ytd": 3.78,
        "w52Low": -8.42,
        "w52High": 3.78,
        "l30d": 5.07,
        "etfProxy": true,
        "ticker": "EWQ"
      },
      "Germany": {
        "ytd": -0.46,
        "w52Low": -10.64,
        "w52High": 3.21,
        "l30d": -0.35,
        "etfProxy": true,
        "ticker": "EWG"
      },
      "Netherlands": {
        "ytd": 19.26,
        "w52Low": -15.22,
        "w52High": 22.73,
        "l30d": 5.61,
        "etfProxy": true,
        "ticker": "EWN"
      },
      "Spain": {
        "ytd": 11.02,
        "w52Low": -19.94,
        "w52High": 11.02,
        "l30d": 8.47,
        "etfProxy": true,
        "ticker": "EWP"
      },
      "Italy": {
        "ytd": 11.43,
        "w52Low": -13.65,
        "w52High": 11.62,
        "l30d": 5.88,
        "etfProxy": true,
        "ticker": "EWI"
      },
      "Finland": {
        "ytd": 12.1,
        "w52Low": -15.87,
        "w52High": 16.02,
        "l30d": -3.38,
        "etfProxy": true,
        "ticker": "EFNL"
      },
      "Belgium": {
        "ytd": 12.9,
        "w52Low": -10.12,
        "w52High": 13.88,
        "l30d": 3.66,
        "etfProxy": true,
        "ticker": "EWK"
      }
    }
  },
  "longTermMarkets": [
    {
      "name": "CH Market (SPI)",
      "group": "Stocks",
      "index": "SPI TR (SIX index) + CHSPI.SW UCITS",
      "ticker": "CHSPI.SW + SPI TR (SIX)",
      "returns": {
        "1": 13.76,
        "5": 6.89,
        "10": 9.26,
        "15": 8.72,
        "20": 6.27
      }
    },
    {
      "name": "US Stock Market",
      "group": "Stocks",
      "index": "iShares Core S&P 500 UCITS ETF (LSE USD, Irish domicile, since 2010)",
      "ticker": "CSPX.L",
      "returns": {
        "1": 23.56,
        "5": 10.64,
        "10": 12.6,
        "15": 13.3,
        "20": null
      }
    },
    {
      "name": "Intl Developed ex US",
      "group": "Stocks",
      "index": "iShares MSCI World ex-US UCITS ETF (LSE, Irish domicile, since 2014)",
      "ticker": "IWQU.L",
      "returns": {
        "1": 16.54,
        "5": 6.16,
        "10": 8.8,
        "15": null,
        "20": null
      }
    },
    {
      "name": "Emerging Markets",
      "group": "Stocks",
      "index": "iShares MSCI EM UCITS ETF (SIX, Irish domicile, since 2009)",
      "ticker": "IEEM.SW",
      "returns": {
        "1": 47.57,
        "5": 4.52,
        "10": 7.78,
        "15": 3.92,
        "20": null
      }
    },
    {
      "name": "Global Real Estate",
      "group": "Stocks",
      "index": "iShares Dev. Mkts Property Yield UCITS ETF (LSE, Irish domicile, since 2009, unhedged CHF)",
      "ticker": "IWDP.L",
      "returns": {
        "1": 3.23,
        "5": -4.52,
        "10": -2.1,
        "15": 0.73,
        "20": null
      }
    },
    {
      "name": "Swiss Real Estate",
      "group": "Stocks",
      "index": "iShares Swiss Real Estate ETF (SIX, since 2011)",
      "ticker": "SRECHA.SW",
      "returns": {
        "1": 7.54,
        "5": 4.07,
        "10": 5.19,
        "15": 4.84,
        "20": null
      }
    },
    {
      "name": "Swiss Bond Index",
      "group": "Bonds",
      "index": "iShares CHF Corp Bond ETF (SIX, UCITS, since 2014)",
      "ticker": "CHCORP.SW",
      "returns": {
        "1": 0.81,
        "5": 1.03,
        "10": 0.86,
        "15": null,
        "20": null
      }
    },
    {
      "name": "Global Bonds (CHF hedged)",
      "group": "Bonds",
      "index": "iShares Core Gbl Agg Bond CHF Hdgd UCITS ETF (SIX, since 2018)",
      "ticker": "AGGH.SW",
      "returns": {
        "1": 1.79,
        "5": -1.22,
        "10": null,
        "15": null,
        "20": null
      }
    }
  ],
  "worldMktCap": {
    "baseline": "2026-03-31",
    "updatedTo": "25.06.2026",
    "totalT": 105.6,
    "regions": [
      {
        "name": "US Market",
        "trillions": 65.9,
        "color": "#003a5c",
        "pct": 62
      },
      {
        "name": "International Developed",
        "trillions": 27.2,
        "color": "#b8922a",
        "pct": 26
      },
      {
        "name": "Emerging Markets",
        "trillions": 12.5,
        "color": "#5a7a3a",
        "pct": 12
      }
    ]
  },
  "mag7": {
    "totalT": 19.1,
    "worldPct": 16,
    "usPct": 26,
    "stocks": [
      {
        "name": "Apple",
        "ticker": "AAPL",
        "trillions": 3.776,
        "totalT": 3.11,
        "freeFloat": 99.5,
        "note": "live"
      },
      {
        "name": "Microsoft",
        "ticker": "MSFT",
        "trillions": 3.402,
        "totalT": 2.83,
        "freeFloat": 99.5,
        "note": "live"
      },
      {
        "name": "Nvidia",
        "ticker": "NVDA",
        "trillions": 2.924,
        "totalT": 2.52,
        "freeFloat": 97.5,
        "note": "live"
      },
      {
        "name": "Amazon",
        "ticker": "AMZN",
        "trillions": 2.511,
        "totalT": 2.07,
        "freeFloat": 94.0,
        "note": "live"
      },
      {
        "name": "Alphabet",
        "ticker": "GOOGL/GOOG",
        "trillions": 4.045,
        "totalT": 1.98,
        "freeFloat": 93.0,
        "note": "MSCI A+C combined"
      },
      {
        "name": "Meta",
        "ticker": "META",
        "trillions": 1.525,
        "totalT": 1.61,
        "freeFloat": 86.0,
        "note": "live"
      },
      {
        "name": "Tesla",
        "ticker": "TSLA",
        "trillions": 0.802,
        "totalT": 0.79,
        "freeFloat": 84.0,
        "note": "live"
      },
      {
        "name": "SpaceX",
        "ticker": "SPCX",
        "trillions": 0.104,
        "totalT": 2.419,
        "freeFloat": 4.3,
        "note": "fallback"
      }
    ]
  }
};
