// AUTO-GENERATED by fetch_data.py  –  08.07.2026 11:46
// Do not edit manually. Re-fetch: python3 fetch_data.py

const LIVE_DATA = {
  "fetchedAt": "08.07.2026 11:46",
  "ytdYear": 2026,
  "mainMarkets": {
    "Emerging Market Equities": {
      "ytd": 19.81,
      "w52Low": -14.94,
      "w52High": 28.55,
      "l30d": 3.76,
      "etfProxy": true,
      "ticker": "EEM"
    },
    "Japanese Equities": {
      "ytd": 17.36,
      "w52Low": -13.77,
      "w52High": 20.9,
      "l30d": 4.64,
      "etfProxy": true,
      "ticker": "EWJ"
    },
    "Global Equities – Small Caps": {
      "ytd": 14.56,
      "w52Low": -9.46,
      "w52High": 17.58,
      "l30d": 1.64,
      "etfProxy": true,
      "ticker": "IUSN.DE"
    },
    "US Equities (S&P 500)": {
      "ytd": 12.23,
      "w52Low": -8.74,
      "w52High": 12.23,
      "l30d": 3.11,
      "etfProxy": true,
      "ticker": "SPY"
    },
    "Global Equities": {
      "ytd": 12.73,
      "w52Low": -9.62,
      "w52High": 13.2,
      "l30d": 3.48,
      "etfProxy": true,
      "ticker": "ACWI"
    },
    "Global Equities Ex-US (MSCI W ex USA)": {
      "ytd": 9.75,
      "w52Low": -9.62,
      "w52High": 11.19,
      "l30d": 2.2,
      "etfProxy": true,
      "ticker": "IWQU.L"
    },
    "Pacific ex Japan Equities": {
      "ytd": 8.68,
      "w52Low": -4.57,
      "w52High": 9.54,
      "l30d": 4.04,
      "etfProxy": true,
      "ticker": "EPP"
    },
    "Swiss Equities – Small Caps": {
      "ytd": 7.2,
      "w52Low": -7.26,
      "w52High": 9.89,
      "l30d": 4.53,
      "etfProxy": true,
      "ticker": "CSSMIM.SW"
    },
    "UK Equities": {
      "ytd": 9.67,
      "w52Low": -11.43,
      "w52High": 9.67,
      "l30d": 4.57,
      "etfProxy": true,
      "ticker": "EWU"
    },
    "Swiss Equities (SPI)": {
      "ytd": 8.9,
      "w52Low": -9.31,
      "w52High": 11.49,
      "l30d": 4.98,
      "etfProxy": true,
      "ticker": "CHSPI.SW"
    },
    "Eurozone Equities (EURO STOXX 50)": {
      "ytd": 8.96,
      "w52Low": -12.06,
      "w52High": 9.05,
      "l30d": 5.77,
      "etfProxy": true,
      "ticker": "FEZ"
    },
    "US Real Estate (Equities)": {
      "ytd": 15.6,
      "w52Low": -0.4,
      "w52High": 16.18,
      "l30d": 4.05,
      "etfProxy": true,
      "ticker": "VNQ"
    },
    "Swiss Real Estate (SXI Broad)": {
      "ytd": 2.34,
      "w52Low": -6.85,
      "w52High": 3.83,
      "l30d": 3.37,
      "etfProxy": true,
      "ticker": "SRFCHA.SW"
    },
    "European Real Estate (Equities)": {
      "ytd": 0.83,
      "w52Low": -3.71,
      "w52High": 11.62,
      "l30d": 1.81,
      "etfProxy": true,
      "ticker": "IPRP.AS"
    },
    "Asian Real Estate (Equities)": {
      "ytd": 0.86,
      "w52Low": -6.76,
      "w52High": 5.11,
      "l30d": 6.33,
      "etfProxy": true,
      "ticker": "RWX"
    },
    "Commodities (Diversified, unhedged)": {
      "ytd": 21.1,
      "w52Low": -8.23,
      "w52High": 29.16,
      "l30d": -2.47,
      "etfProxy": true,
      "ticker": "ICOM.L"
    },
    "Gold Bullion (unhedged)": {
      "ytd": -5.19,
      "w52Low": -22.88,
      "w52High": 16.73,
      "l30d": -5.1,
      "etfProxy": true,
      "ticker": "ZGLD.SW"
    },
    "CHF Bonds": {
      "ytd": 0.32,
      "w52Low": -1.21,
      "w52High": 0.89,
      "l30d": 0.57,
      "etfProxy": true,
      "ticker": "CHCORP.SW"
    },
    "EM Bonds Local Currency": {
      "ytd": 3.04,
      "w52Low": -5.8,
      "w52High": 3.04,
      "l30d": 3.36,
      "etfProxy": true,
      "ticker": "EMLC"
    },
    "Global Bonds (CHF hedged)": {
      "ytd": -0.38,
      "w52Low": -1.78,
      "w52High": 1.05,
      "l30d": 0.31,
      "etfProxy": true,
      "ticker": "AGGH.SW"
    },
    "EUR Bonds": {
      "ytd": 0.57,
      "w52Low": -2.73,
      "w52High": 13.72,
      "l30d": 2.08,
      "etfProxy": true,
      "ticker": "IBGE.L"
    },
    "USD Bonds": {
      "ytd": 1.99,
      "w52Low": -3.68,
      "w52High": 3.05,
      "l30d": 1.83,
      "etfProxy": true,
      "ticker": "AGG"
    },
    "CHF Corporate Bonds": {
      "ytd": 0.32,
      "w52Low": -1.21,
      "w52High": 0.89,
      "l30d": 0.57,
      "etfProxy": true,
      "ticker": "CHCORP.SW"
    },
    "USD Corporate Bonds": {
      "ytd": 1.77,
      "w52Low": -3.61,
      "w52High": 3.16,
      "l30d": 1.53,
      "etfProxy": true,
      "ticker": "LQD"
    },
    "EUR Corporate Bonds": {
      "ytd": -0.08,
      "w52Low": -2.47,
      "w52High": 1.17,
      "l30d": 0.52,
      "etfProxy": true,
      "ticker": "IEAC.AS"
    },
    "Inflation Linked": {
      "ytd": 1.92,
      "w52Low": -2.09,
      "w52High": 2.71,
      "l30d": 1.43,
      "etfProxy": true,
      "ticker": "TIP"
    },
    "Money Market CHF": {
      "ytd": -0.61,
      "w52Low": -2.39,
      "w52High": 1.68,
      "l30d": 0.43,
      "etfProxy": true,
      "ticker": "CSBGC0.SW"
    },
    "Money Market GBP": {
      "ytd": 3.2,
      "w52Low": -2.49,
      "w52High": 3.2,
      "l30d": 1.82,
      "etfProxy": true,
      "ticker": "CSH2.L"
    },
    "Money Market USD": {
      "ytd": 3.51,
      "w52Low": -2.45,
      "w52High": 3.64,
      "l30d": 1.75,
      "etfProxy": true,
      "ticker": "BIL"
    },
    "Money Market EUR": {
      "ytd": -0.22,
      "w52Low": -2.79,
      "w52High": 0.88,
      "l30d": 0.53,
      "etfProxy": true,
      "ticker": "EXVM.DE"
    },
    "USD / CHF": {
      "ytd": 2.0,
      "w52Low": -2.83,
      "w52High": 2.77,
      "l30d": 1.45,
      "etfProxy": true,
      "ticker": "USDCHF=X"
    },
    "EUR / CHF": {
      "ytd": -0.87,
      "w52Low": -3.02,
      "w52High": 1.49,
      "l30d": 0.35,
      "etfProxy": true,
      "ticker": "EURCHF=X"
    },
    "JPY / CHF": {
      "ytd": -1.57,
      "w52Low": -2.81,
      "w52High": 8.5,
      "l30d": 0.14,
      "etfProxy": true,
      "ticker": "JPYCHF=X"
    }
  },
  "subMarkets": {
    "Emerging Market Equities": {
      "Taiwan": {
        "ytd": 60.44,
        "w52Low": -13.47,
        "w52High": 72.53,
        "l30d": 5.38,
        "etfProxy": true,
        "ticker": "EWT"
      },
      "China": {
        "ytd": -14.58,
        "w52Low": -16.72,
        "w52High": 5.4,
        "l30d": -2.87,
        "etfProxy": true,
        "ticker": "MCHI"
      },
      "South Korea": {
        "ytd": 80.9,
        "w52Low": -31.39,
        "w52High": 117.86,
        "l30d": 4.98,
        "etfProxy": true,
        "ticker": "EWY"
      },
      "India": {
        "ytd": -7.78,
        "w52Low": -15.69,
        "w52High": 1.65,
        "l30d": 5.71,
        "etfProxy": true,
        "ticker": "INDA"
      },
      "South Africa": {
        "ytd": -4.49,
        "w52Low": -27.22,
        "w52High": 14.49,
        "l30d": 2.42,
        "etfProxy": true,
        "ticker": "EZA"
      },
      "Brazil": {
        "ytd": 10.77,
        "w52Low": -19.46,
        "w52High": 27.91,
        "l30d": 4.31,
        "etfProxy": true,
        "ticker": "EWZ"
      },
      "Saudi Arabia": {
        "ytd": 5.42,
        "w52Low": -1.57,
        "w52High": 10.21,
        "l30d": 2.97,
        "etfProxy": true,
        "ticker": "KSA"
      },
      "Mexico": {
        "ytd": 11.49,
        "w52Low": -15.12,
        "w52High": 14.44,
        "l30d": 2.86,
        "etfProxy": true,
        "ticker": "EWW"
      },
      "UAE": {
        "ytd": 5.32,
        "w52Low": -9.59,
        "w52High": 11.36,
        "l30d": 8.8,
        "etfProxy": true,
        "ticker": "UAE"
      },
      "Indonesia": {
        "ytd": -33.59,
        "w52Low": -39.97,
        "w52High": 3.13,
        "l30d": 10.63,
        "etfProxy": true,
        "ticker": "EIDO"
      },
      "Thailand": {
        "ytd": 25.29,
        "w52Low": -14.07,
        "w52High": 25.51,
        "l30d": 2.94,
        "etfProxy": true,
        "ticker": "THD"
      }
    },
    "US Equities (S&P 500)": {
      "Nasdaq 100": {
        "ytd": 18.3,
        "w52Low": -9.34,
        "w52High": 22.88,
        "l30d": 2.19,
        "etfProxy": true,
        "ticker": "QQQ"
      },
      "Russell 2000": {
        "ytd": 21.94,
        "w52Low": -12.86,
        "w52High": 23.72,
        "l30d": 6.94,
        "etfProxy": true,
        "ticker": "IWM"
      }
    },
    "Swiss Equities (SPI)": {
      "SMI": {
        "ytd": 9.31,
        "w52Low": -10.86,
        "w52High": 11.66,
        "l30d": 5.54,
        "etfProxy": true,
        "ticker": "CSSMI.SW"
      },
      "SPI Extra": {
        "ytd": 7.2,
        "w52Low": -7.26,
        "w52High": 9.89,
        "l30d": 4.53,
        "etfProxy": true,
        "ticker": "CSSMIM.SW"
      }
    },
    "Eurozone Equities (EURO STOXX 50)": {
      "France": {
        "ytd": 4.87,
        "w52Low": -8.42,
        "w52High": 5.17,
        "l30d": 4.19,
        "etfProxy": true,
        "ticker": "EWQ"
      },
      "Germany": {
        "ytd": 2.8,
        "w52Low": -10.64,
        "w52High": 3.21,
        "l30d": 3.34,
        "etfProxy": true,
        "ticker": "EWG"
      },
      "Netherlands": {
        "ytd": 18.02,
        "w52Low": -15.22,
        "w52High": 23.94,
        "l30d": 4.93,
        "etfProxy": true,
        "ticker": "EWN"
      },
      "Spain": {
        "ytd": 13.33,
        "w52Low": -19.94,
        "w52High": 13.33,
        "l30d": 8.57,
        "etfProxy": true,
        "ticker": "EWP"
      },
      "Italy": {
        "ytd": 14.25,
        "w52Low": -13.65,
        "w52High": 14.25,
        "l30d": 8.0,
        "etfProxy": true,
        "ticker": "EWI"
      },
      "Finland": {
        "ytd": 10.05,
        "w52Low": -15.87,
        "w52High": 16.02,
        "l30d": -3.84,
        "etfProxy": true,
        "ticker": "EFNL"
      },
      "Belgium": {
        "ytd": 12.99,
        "w52Low": -9.92,
        "w52High": 14.05,
        "l30d": 3.03,
        "etfProxy": true,
        "ticker": "EWK"
      }
    }
  },
  "longTermMarkets": [
    {
      "name": "CH Market (SPI)",
      "group": "Stocks",
      "index": "SPI TR (SIX index) + CHSPI.SW UCITS",
      "ticker": "CHSPI.SW + SPI TR (SIX)",
      "returns": {
        "1": 21.31,
        "5": 6.77,
        "10": 9.97,
        "15": 9.04,
        "20": 6.79
      }
    },
    {
      "name": "US Stock Market",
      "group": "Stocks",
      "index": "iShares Core S&P 500 UCITS ETF (LSE USD, Irish domicile, since 2010)",
      "ticker": "CSPX.L",
      "returns": {
        "1": 23.5,
        "5": 10.14,
        "10": 13.02,
        "15": 13.78,
        "20": null
      }
    },
    {
      "name": "Intl Developed ex US",
      "group": "Stocks",
      "index": "iShares MSCI World ex-US UCITS ETF (LSE, Irish domicile, since 2014)",
      "ticker": "IWQU.L",
      "returns": {
        "1": 17.5,
        "5": 6.47,
        "10": 10.27,
        "15": null,
        "20": null
      }
    },
    {
      "name": "Emerging Markets",
      "group": "Stocks",
      "index": "iShares MSCI EM UCITS ETF (SIX, Irish domicile, since 2009)",
      "ticker": "IEEM.SW",
      "returns": {
        "1": 46.52,
        "5": 4.68,
        "10": 7.79,
        "15": 4.33,
        "20": null
      }
    },
    {
      "name": "Global Real Estate",
      "group": "Stocks",
      "index": "iShares Dev. Mkts Property Yield UCITS ETF (LSE, Irish domicile, since 2009, unhedged CHF)",
      "ticker": "IWDP.L",
      "returns": {
        "1": 10.37,
        "5": -4.45,
        "10": -2.04,
        "15": 1.3,
        "20": null
      }
    },
    {
      "name": "Swiss Real Estate",
      "group": "Stocks",
      "index": "iShares Swiss Real Estate ETF (SIX, since 2011)",
      "ticker": "SRECHA.SW",
      "returns": {
        "1": 7.87,
        "5": 3.04,
        "10": 5.16,
        "15": 4.92,
        "20": null
      }
    },
    {
      "name": "Swiss Bond Index",
      "group": "Bonds",
      "index": "iShares CHF Corp Bond ETF (SIX, UCITS, since 2014)",
      "ticker": "CHCORP.SW",
      "returns": {
        "1": 2.1,
        "5": 1.15,
        "10": 0.86,
        "15": null,
        "20": null
      }
    },
    {
      "name": "Global Bonds (CHF hedged)",
      "group": "Bonds",
      "index": "iShares Core Gbl Agg Bond CHF Hdgd UCITS ETF (SIX, since 2018)",
      "ticker": "AGGH.SW",
      "returns": {
        "1": 1.08,
        "5": -1.34,
        "10": null,
        "15": null,
        "20": null
      }
    }
  ],
  "worldMktCap": {
    "baseline": "2026-03-31",
    "updatedTo": "08.07.2026",
    "totalT": 105.2,
    "regions": [
      {
        "name": "US Market",
        "trillions": 65.2,
        "color": "#003a5c",
        "pct": 62
      },
      {
        "name": "International Developed",
        "trillions": 27.4,
        "color": "#b8922a",
        "pct": 26
      },
      {
        "name": "Emerging Markets",
        "trillions": 12.6,
        "color": "#5a7a3a",
        "pct": 12
      }
    ]
  },
  "mag7": {
    "totalT": 18.0,
    "worldPct": 17,
    "usPct": 27,
    "stocks": [
      {
        "name": "Apple",
        "ticker": "AAPL",
        "trillions": 3.735,
        "totalT": 3.11,
        "freeFloat": 99.5,
        "note": "live"
      },
      {
        "name": "Microsoft",
        "ticker": "MSFT",
        "trillions": 2.951,
        "totalT": 2.83,
        "freeFloat": 99.5,
        "note": "live"
      },
      {
        "name": "Nvidia",
        "ticker": "NVDA",
        "trillions": 2.699,
        "totalT": 2.52,
        "freeFloat": 97.5,
        "note": "live"
      },
      {
        "name": "Amazon",
        "ticker": "AMZN",
        "trillions": 2.251,
        "totalT": 2.07,
        "freeFloat": 94.0,
        "note": "live"
      },
      {
        "name": "Alphabet",
        "ticker": "GOOGL/GOOG",
        "trillions": 4.088,
        "totalT": 1.98,
        "freeFloat": 93.0,
        "note": "MSCI A+C combined"
      },
      {
        "name": "Meta",
        "ticker": "META",
        "trillions": 1.407,
        "totalT": 1.61,
        "freeFloat": 86.0,
        "note": "live"
      },
      {
        "name": "Tesla",
        "ticker": "TSLA",
        "trillions": 0.725,
        "totalT": 0.79,
        "freeFloat": 84.0,
        "note": "live"
      },
      {
        "name": "SpaceX",
        "ticker": "SPCX",
        "trillions": 0.104,
        "totalT": 2.419,
        "freeFloat": 4.3,
        "note": "fallback"
      }
    ]
  }
};
