// AUTO-GENERATED by fetch_data.py  –  16.06.2026 16:02
// Do not edit manually. Re-fetch: python3 fetch_data.py

const LIVE_DATA = {
  "fetchedAt": "16.06.2026 16:02",
  "ytdYear": 2026,
  "mainMarkets": {
    "Emerging Market Equities": {
      "ytd": 24.72,
      "w52Low": -16.92,
      "w52High": 24.72,
      "l30d": 8.48,
      "etfProxy": true,
      "ticker": "EEM"
    },
    "Japanese Equities": {
      "ytd": 17.5,
      "w52Low": -13.77,
      "w52High": 17.5,
      "l30d": 5.6,
      "etfProxy": true,
      "ticker": "EWJ"
    },
    "Global Equities – Small Caps": {
      "ytd": 16.27,
      "w52Low": -10.78,
      "w52High": 16.27,
      "l30d": 6.29,
      "etfProxy": true,
      "ticker": "IUSN.DE"
    },
    "US Equities (S&P 500)": {
      "ytd": 11.12,
      "w52Low": -10.93,
      "w52High": 11.12,
      "l30d": 3.07,
      "etfProxy": true,
      "ticker": "SPY"
    },
    "Global Equities": {
      "ytd": 12.15,
      "w52Low": -11.77,
      "w52High": 12.15,
      "l30d": 4.37,
      "etfProxy": true,
      "ticker": "ACWI"
    },
    "Global Equities Ex-US (MSCI W ex USA)": {
      "ytd": 10.01,
      "w52Low": -9.62,
      "w52High": 10.01,
      "l30d": 5.04,
      "etfProxy": true,
      "ticker": "IWQU.L"
    },
    "Pacific ex Japan Equities": {
      "ytd": 8.71,
      "w52Low": -7.05,
      "w52High": 9.54,
      "l30d": 1.76,
      "etfProxy": true,
      "ticker": "EPP"
    },
    "Swiss Equities – Small Caps": {
      "ytd": 4.49,
      "w52Low": -7.26,
      "w52High": 6.07,
      "l30d": 3.84,
      "etfProxy": true,
      "ticker": "CSSMIM.SW"
    },
    "UK Equities": {
      "ytd": 6.83,
      "w52Low": -13.12,
      "w52High": 7.11,
      "l30d": 4.89,
      "etfProxy": true,
      "ticker": "EWU"
    },
    "Swiss Equities (SPI)": {
      "ytd": 6.3,
      "w52Low": -9.98,
      "w52High": 6.3,
      "l30d": 3.98,
      "etfProxy": true,
      "ticker": "CHSPI.SW"
    },
    "Eurozone Equities (EURO STOXX 50)": {
      "ytd": 7.76,
      "w52Low": -12.06,
      "w52High": 7.76,
      "l30d": 8.97,
      "etfProxy": true,
      "ticker": "FEZ"
    },
    "US Real Estate (Equities)": {
      "ytd": 12.49,
      "w52Low": -1.33,
      "w52High": 13.18,
      "l30d": 5.58,
      "etfProxy": true,
      "ticker": "VNQ"
    },
    "Swiss Real Estate (SXI Broad)": {
      "ytd": 0.83,
      "w52Low": -6.85,
      "w52High": 3.83,
      "l30d": 0.28,
      "etfProxy": true,
      "ticker": "SRFCHA.SW"
    },
    "European Real Estate (Equities)": {
      "ytd": 1.49,
      "w52Low": -3.71,
      "w52High": 11.62,
      "l30d": 2.38,
      "etfProxy": true,
      "ticker": "IPRP.AS"
    },
    "Asian Real Estate (Equities)": {
      "ytd": -1.52,
      "w52Low": -6.8,
      "w52High": 5.11,
      "l30d": 2.17,
      "etfProxy": true,
      "ticker": "RWX"
    },
    "Commodities (Diversified, unhedged)": {
      "ytd": 19.28,
      "w52Low": -8.23,
      "w52High": 29.16,
      "l30d": -7.65,
      "etfProxy": true,
      "ticker": "ICOM.L"
    },
    "Gold Bullion (unhedged)": {
      "ytd": -0.31,
      "w52Low": -23.89,
      "w52High": 16.73,
      "l30d": -3.69,
      "etfProxy": true,
      "ticker": "ZGLD.SW"
    },
    "CHF Bonds": {
      "ytd": 0.42,
      "w52Low": -1.69,
      "w52High": 0.89,
      "l30d": 0.83,
      "etfProxy": true,
      "ticker": "CHCORP.SW"
    },
    "EM Bonds Local Currency": {
      "ytd": 3.11,
      "w52Low": -5.29,
      "w52High": 3.11,
      "l30d": 3.83,
      "etfProxy": true,
      "ticker": "EMLC"
    },
    "Global Bonds (CHF hedged)": {
      "ytd": -0.04,
      "w52Low": -1.78,
      "w52High": 1.05,
      "l30d": 1.1,
      "etfProxy": true,
      "ticker": "AGGH.SW"
    },
    "EUR Bonds": {
      "ytd": 0.2,
      "w52Low": -2.73,
      "w52High": 13.72,
      "l30d": 0.9,
      "etfProxy": true,
      "ticker": "IBGE.L"
    },
    "USD Bonds": {
      "ytd": 1.05,
      "w52Low": -3.68,
      "w52High": 2.18,
      "l30d": 2.24,
      "etfProxy": true,
      "ticker": "AGG"
    },
    "CHF Corporate Bonds": {
      "ytd": 0.42,
      "w52Low": -1.69,
      "w52High": 0.89,
      "l30d": 0.83,
      "etfProxy": true,
      "ticker": "CHCORP.SW"
    },
    "USD Corporate Bonds": {
      "ytd": 1.27,
      "w52Low": -3.61,
      "w52High": 2.17,
      "l30d": 2.52,
      "etfProxy": true,
      "ticker": "LQD"
    },
    "EUR Corporate Bonds": {
      "ytd": 0.29,
      "w52Low": -2.47,
      "w52High": 1.17,
      "l30d": 2.02,
      "etfProxy": true,
      "ticker": "IEAC.AS"
    },
    "Inflation Linked": {
      "ytd": 1.93,
      "w52Low": -2.22,
      "w52High": 2.71,
      "l30d": 1.37,
      "etfProxy": true,
      "ticker": "TIP"
    },
    "Money Market CHF": {
      "ytd": -0.35,
      "w52Low": -3.13,
      "w52High": 1.68,
      "l30d": 1.36,
      "etfProxy": true,
      "ticker": "CSBGC0.SW"
    },
    "Money Market GBP": {
      "ytd": 1.78,
      "w52Low": -2.49,
      "w52High": 2.02,
      "l30d": 1.97,
      "etfProxy": true,
      "ticker": "CSH2.L"
    },
    "Money Market USD": {
      "ytd": 1.9,
      "w52Low": -2.45,
      "w52High": 2.19,
      "l30d": 1.26,
      "etfProxy": true,
      "ticker": "BIL"
    },
    "Money Market EUR": {
      "ytd": -0.4,
      "w52Low": -2.79,
      "w52High": 0.88,
      "l30d": 0.89,
      "etfProxy": true,
      "ticker": "EXVM.DE"
    },
    "USD / CHF": {
      "ytd": 0.34,
      "w52Low": -2.83,
      "w52High": 3.28,
      "l30d": 0.97,
      "etfProxy": true,
      "ticker": "USDCHF=X"
    },
    "EUR / CHF": {
      "ytd": -0.92,
      "w52Low": -3.02,
      "w52High": 1.49,
      "l30d": 0.69,
      "etfProxy": true,
      "ticker": "EURCHF=X"
    },
    "JPY / CHF": {
      "ytd": -1.88,
      "w52Low": -2.81,
      "w52High": 10.9,
      "l30d": -0.0,
      "etfProxy": true,
      "ticker": "JPYCHF=X"
    }
  },
  "subMarkets": {
    "Emerging Market Equities": {
      "Taiwan": {
        "ytd": 63.67,
        "w52Low": -16.39,
        "w52High": 63.67,
        "l30d": 16.87,
        "etfProxy": true,
        "ticker": "EWT"
      },
      "China": {
        "ytd": -12.26,
        "w52Low": -13.15,
        "w52High": 5.4,
        "l30d": -2.97,
        "etfProxy": true,
        "ticker": "MCHI"
      },
      "South Korea": {
        "ytd": 107.91,
        "w52Low": -32.28,
        "w52High": 107.91,
        "l30d": 19.57,
        "etfProxy": true,
        "ticker": "EWY"
      },
      "India": {
        "ytd": -9.09,
        "w52Low": -15.69,
        "w52High": 4.56,
        "l30d": 4.01,
        "etfProxy": true,
        "ticker": "INDA"
      },
      "South Africa": {
        "ytd": 1.01,
        "w52Low": -27.87,
        "w52High": 14.49,
        "l30d": 4.73,
        "etfProxy": true,
        "ticker": "EZA"
      },
      "Brazil": {
        "ytd": 8.94,
        "w52Low": -19.19,
        "w52High": 28.35,
        "l30d": -2.9,
        "etfProxy": true,
        "ticker": "EWZ"
      },
      "Saudi Arabia": {
        "ytd": 7.27,
        "w52Low": -1.57,
        "w52High": 10.21,
        "l30d": 3.66,
        "etfProxy": true,
        "ticker": "KSA"
      },
      "Mexico": {
        "ytd": 14.33,
        "w52Low": -16.96,
        "w52High": 14.33,
        "l30d": 3.81,
        "etfProxy": true,
        "ticker": "EWW"
      },
      "UAE": {
        "ytd": 6.14,
        "w52Low": -11.19,
        "w52High": 10.95,
        "l30d": 8.48,
        "etfProxy": true,
        "ticker": "UAE"
      },
      "Indonesia": {
        "ytd": -30.97,
        "w52Low": -39.91,
        "w52High": 3.24,
        "l30d": -7.68,
        "etfProxy": true,
        "ticker": "EIDO"
      },
      "Thailand": {
        "ytd": 25.08,
        "w52Low": -18.9,
        "w52High": 25.19,
        "l30d": 6.08,
        "etfProxy": true,
        "ticker": "THD"
      }
    },
    "US Equities (S&P 500)": {
      "Nasdaq 100": {
        "ytd": 21.68,
        "w52Low": -11.57,
        "w52High": 21.68,
        "l30d": 5.77,
        "etfProxy": true,
        "ticker": "QQQ"
      },
      "Russell 2000": {
        "ytd": 19.96,
        "w52Low": -13.92,
        "w52High": 19.96,
        "l30d": 8.0,
        "etfProxy": true,
        "ticker": "IWM"
      }
    },
    "Swiss Equities (SPI)": {
      "SMI": {
        "ytd": 6.53,
        "w52Low": -10.86,
        "w52High": 6.53,
        "l30d": 4.23,
        "etfProxy": true,
        "ticker": "CSSMI.SW"
      },
      "SPI Extra": {
        "ytd": 4.49,
        "w52Low": -7.26,
        "w52High": 6.07,
        "l30d": 3.84,
        "etfProxy": true,
        "ticker": "CSSMIM.SW"
      }
    },
    "Eurozone Equities (EURO STOXX 50)": {
      "France": {
        "ytd": 4.6,
        "w52Low": -8.44,
        "w52High": 4.6,
        "l30d": 8.0,
        "etfProxy": true,
        "ticker": "EWQ"
      },
      "Germany": {
        "ytd": 1.19,
        "w52Low": -10.64,
        "w52High": 3.21,
        "l30d": 4.76,
        "etfProxy": true,
        "ticker": "EWG"
      },
      "Netherlands": {
        "ytd": 20.58,
        "w52Low": -15.22,
        "w52High": 20.58,
        "l30d": 10.41,
        "etfProxy": true,
        "ticker": "EWN"
      },
      "Spain": {
        "ytd": 9.64,
        "w52Low": -21.39,
        "w52High": 9.64,
        "l30d": 8.49,
        "etfProxy": true,
        "ticker": "EWP"
      },
      "Italy": {
        "ytd": 12.66,
        "w52Low": -15.8,
        "w52High": 12.66,
        "l30d": 8.46,
        "etfProxy": true,
        "ticker": "EWI"
      },
      "Finland": {
        "ytd": 14.57,
        "w52Low": -18.63,
        "w52High": 16.02,
        "l30d": 3.18,
        "etfProxy": true,
        "ticker": "EFNL"
      },
      "Belgium": {
        "ytd": 12.51,
        "w52Low": -10.42,
        "w52High": 13.88,
        "l30d": 5.74,
        "etfProxy": true,
        "ticker": "EWK"
      }
    }
  },
  "longTermMarkets": [
    {
      "name": "CH Market (SPI)",
      "group": "Stocks",
      "index": "SPI TR (SIX index) + CHSPI.SW UCITS",
      "ticker": "CHSPI.SW + SPI TR (SIX)",
      "returns": {
        "1": 13.76,
        "5": 6.89,
        "10": 9.26,
        "15": 8.72,
        "20": 6.27
      }
    },
    {
      "name": "US Stock Market",
      "group": "Stocks",
      "index": "iShares Core S&P 500 UCITS ETF (LSE USD, Irish domicile, since 2010)",
      "ticker": "CSPX.L",
      "returns": {
        "1": 23.56,
        "5": 10.64,
        "10": 12.6,
        "15": 13.3,
        "20": null
      }
    },
    {
      "name": "Intl Developed ex US",
      "group": "Stocks",
      "index": "iShares MSCI World ex-US UCITS ETF (LSE, Irish domicile, since 2014)",
      "ticker": "IWQU.L",
      "returns": {
        "1": 16.54,
        "5": 6.16,
        "10": 8.8,
        "15": null,
        "20": null
      }
    },
    {
      "name": "Emerging Markets",
      "group": "Stocks",
      "index": "iShares MSCI EM UCITS ETF (SIX, Irish domicile, since 2009)",
      "ticker": "IEEM.SW",
      "returns": {
        "1": 47.57,
        "5": 4.52,
        "10": 7.78,
        "15": 3.92,
        "20": null
      }
    },
    {
      "name": "Global Real Estate",
      "group": "Stocks",
      "index": "iShares Dev. Mkts Property Yield UCITS ETF (LSE, Irish domicile, since 2009, unhedged CHF)",
      "ticker": "IWDP.L",
      "returns": {
        "1": 3.23,
        "5": -4.52,
        "10": -2.1,
        "15": 0.73,
        "20": null
      }
    },
    {
      "name": "Swiss Real Estate",
      "group": "Stocks",
      "index": "iShares Swiss Real Estate ETF (SIX, since 2011)",
      "ticker": "SRECHA.SW",
      "returns": {
        "1": 7.54,
        "5": 4.07,
        "10": 5.19,
        "15": 4.84,
        "20": null
      }
    },
    {
      "name": "Swiss Bond Index",
      "group": "Bonds",
      "index": "iShares CHF Corp Bond ETF (SIX, UCITS, since 2014)",
      "ticker": "CHCORP.SW",
      "returns": {
        "1": 0.81,
        "5": 1.03,
        "10": 0.86,
        "15": null,
        "20": null
      }
    },
    {
      "name": "Global Bonds (CHF hedged)",
      "group": "Bonds",
      "index": "iShares Core Gbl Agg Bond CHF Hdgd UCITS ETF (SIX, since 2018)",
      "ticker": "AGGH.SW",
      "returns": {
        "1": 1.79,
        "5": -1.22,
        "10": null,
        "15": null,
        "20": null
      }
    }
  ],
  "worldMktCap": {
    "baseline": "2026-03-31",
    "updatedTo": "16.06.2026",
    "totalT": 105.6,
    "regions": [
      {
        "name": "US Market",
        "trillions": 65.9,
        "color": "#003a5c",
        "pct": 62
      },
      {
        "name": "International Developed",
        "trillions": 27.2,
        "color": "#b8922a",
        "pct": 26
      },
      {
        "name": "Emerging Markets",
        "trillions": 12.5,
        "color": "#5a7a3a",
        "pct": 12
      }
    ]
  }
};
